services:
  api:
    container_name: text2pdf-api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    env_file:
      - .env

  alpine:
    container_name: text2pdf-alpine
    build:
      context: .
      dockerfile: Dockerfiles/alpine.Dockerfile
    ports:
      - 3000:3000
    env_file:
      - .env
      
  debian:
    container_name: text2pdf-debian
    build:
      context: .
      dockerfile: Dockerfiles/debian.Dockerfile
    ports:
      - 3000:3000
    env_file:
      - .env

    